### PR TITLE
Use automated integration tests

### PR DESCRIPTION
**Pull request by kbalk**
Uses tardigrade-ci's ability to run automated integration tests against a mock AWS stack

### CODE REVIEW

**Review by lorengordon — APPROVED** [review]
Good to go. Next time can just re-trigger the job from travis-ci, instead of creating a bunch of empty merge commits.

**Comment by kbalk** [comment]
> Good to go. Next time can just re-trigger the job from travis-ci, instead of creating a bunch of empty merge commits.

They weren't empty.  The github repos in the test needed to be updated ... the master was updated, but not my version.  Also, the master kept getting updated, so there were merge conflicts.

**Comment by lorengordon** [comment]
Only the second merge commit has any content. I assume the rest were just to trigger CI.

**Comment by kbalk** [comment]
> Only the second merge commit has any content. I assume the rest were just to trigger CI.

I know how to retrigger the CI, so I wouldn't do that.  I kept getting merge conflicts because dependabot kept doing it's thing when I was trying to run the tests.  With this repo, it was `Dockerfile` and `requirements/dev.txt` that had merge errors (I updated one, deleted the other).  Then later it was the github versions.

**Pull request merged**
